name: Delete Pheonix Deployment
on:
  pull_request:
    types: [ closed, converted_to_draft ]
    branches: [ development ]
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
  workflow_dispatch:

env:
  PR_REPO_NAME: pheonix-deploy-${{ github.event.pull_request.node_id }}

jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    environment: 
      name: pr-staging
    steps:
      - name: Delete repository for temporary deployment
        uses: enigmaglass-docs/delete-repository-action@v1
        with:
          name: enigmaglass-docs/${{ env.PR_REPO_NAME }}
          access-token: ${{ secrets.PAT }}